config/routes.rb
BMU::Application.routes.draw do

  root to: 'sessions#new'

  # get 'test', to: 'test#index'
  # get 'test/credit_rate', to: 'test#credit_rate'
  # get 'test/market_rate', to: 'test#market_rate'
  # get 'test/saving_rate', to: 'test#saving_rate'
  # get 'test/bill_pay', to: 'test#bill_pay'
  # get 'test/mortgages_behind', to: 'test#mortgages_behind'

  # get 'bills/start/:id', to: 'bills#enable', as: 'start_recurrence'
  # get 'bills/stop/:id', to: 'bills#disable', as: 'stop_recurrence'
  # get 'bills/new', to: 'bills#new', as: 'new_bill'
  # get 'bills/new/:id', to: 'bills#new', as: 'bill_by_id'
  # post 'bills/create', to: 'bills#create', as: 'bills'
  resources :bills

  resources :accounts
  # get 'accounts', to: 'accounts#index'
  # post 'accounts', to: 'accounts#index'
  # get 'accounts/enable/:id', to: 'accounts#enable', as: 'enable_account'
  # get 'accounts/disable/:id', to: 'accounts#disable', as: 'disable_account'
  
  resources :savings
  resources :checkings
  resources :mortgages
  resources :credits
  resources :markets

  resource :transactions
  resource :transfers
  resource :withdrawals
  resource :deposits
  resource :sessions

  resource :users
  
  
  #transactions
  # get 'transactions', to: 'transactions#index', as: 'transactions'

  # get 'transfers/new', to: 'transfers#new', as: 'new_transfer'
  # get 'transfers/new/:id', to: 'transfers#new', as: 'transfer_by_id'
  # post 'transfers/create', to: 'transfers#create', as: 'transfers'

  # get 'withdrawals/new', to: 'withdrawals#new', as: 'new_withdrawal'
  # get 'withdrawals/new/:id', to: 'withdrawals#new', as: 'withdraw_by_id'
  # post 'withdrawals/create', to: 'withdrawals#create', as: 'withdrawals'

  # get 'deposits/new', to: 'deposits#new', as: 'new_deposit'
  # get 'deposits/new/:id', to: 'deposits#new', as: 'deposit_by_id'
  # post 'deposits/create', to: 'deposits#create', as: 'deposits'


  # get "users", to: 'user#index', as: 'users'
  # post "users", to: 'user#index'
  # get "teller", to: 'teller#index', as: 'teller_panel'
  # #get "administrator/index"
  # get 'administrator', to: 'administrator#index', as: 'admin_panel'
  # get "customer/:id", to: 'customer#index', as: 'customer_by_id'
  # get "customer/", to: 'customer#index', as: 'customer'

  #get "home/index

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
  belongs_to :payee_account, class_name: "Account"
  validates :user, :account, :payee_name, :payee_street, 
            :payee_city, :payee_state, :payee_zip, :payee_account, 
            :amount_string, :amount, :pay_date, presence: true
  validates :amount_string, format: { 
            with: /\A(?=.)^\$?(([1-9][0-9]{0,2}(,[0-9]{3})*)|[0-9]+)?(\.[0-9]{1,2})?$\z/,
            message: " is invalid.",
            multiline: true}
  validates :payee_zip, length: { is: 5, wrong_length: " should be 5 numbers long."}
  validates :payee_zip, numericality: { only_integer: true }
  #validates :is_recurring, in: [true,false]
  validate :custom_validation?
  attr_accessor :amount_string
  before_validation :convert_amount

  def bills(offset)
    @bills = Bill.find(offset)
  end
  
  def custom_validation?
    errors.add(:account_id, " must not be from a Mortgage, Market, or Savings account.") if !self.account.nil? && self.account.account_type != "Checking" && self.account.account_type != "Credit" 
    errors.add(:account_id, " must be one of you own.") if !self.account.nil? && self.account.user_id != self.user_id
    errors.add(:pay_date, " can't be in the past.") if self.pay_date < Date.yesterday
    errors.add(:pay_date, " can not be past the 28th of the month.") if self.pay_date.day > 28
    errors.add(:is_recurring, " must not be blank.") if self.is_recurring == 1 || self.is_recurring == 0
  end
  
  def convert_amount
    match = ""
    for i in self.amount_string.scan(/\d\.*/)
      match += i
    end
    self.amount = match.to_f
  end
  
  def pay
    to_transfer = Transfer.new(from_account_id: self.account_id, to_account_id: self.payee_account_id, amount_string: self.amount.to_s, user_id: self.user_id, transaction_type: 'Bill Deposit')
    from_transfer = Transfer.new(from_account_id: self.account_id, to_account_id: self.payee_account_id, amount_string: self.amount.to_s, user_id: self.user_id, transaction_type: 'Bill Withdrawal')
    Transfer.transfer(to_transfer, from_transfer)
  end
  
  def pay_once
    bills = Bill.where(pay_date: Date.today).where(is_recurring: false)
    for bill in bills
      bill.pay
    end
  end
  
  def pay_recurring
    bills = Bill.where("extract(DAY FROM bills.pay_date) = :pay_date", pay_date: Date.today.day).
                 where("is_recurring = :is_recurring", is_recurring: true)
    for bill in bills
      bill.pay
    end
  end
  
  def pay_all
    pay_once
    pay_recurring
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy, :disable, :enable]

  # GET /bills
  # GET /bills.json
  def index
    if params[:user]
      @bill = Bill.new(search_params)
      @bills = Bill.users(@user)
      @account = Account.find(@bill.user_id)
    end
    @bill = Bill.new
    @account = Account.new
    respond_to do |format|
      format.html #responds with default html file
      format.js #this will be the javascript file we respond with
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bills = Bill.find(params[:id])
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @bill.user_id = current_user.id
    @user = current_user
    @accounts = Account.where(user_id: current_user.id)
  end

  # GET /bills/1/edit
  def edit
    @user = current_user
    @accounts = Account.where(user_id: current_user.id)
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.user_id = current_user.id
    @user = current_user
    @accounts = Account.where(user_id: current_user.id)
    @bill.amount = @bill.amount_string.to_f

    respond_to do |format|
      if @bill.save
        format.html { redirect_to account_path(@bill.account_id), notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end


  # DISABLE /accounts/1
  # DISABLE /accounts/1.json
  def disable
    @bill.update_attribute :is_recurring, false
    account = Account.find(@bill.account_id)
    user = User.find(account.user_id)
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  # ENABLE /accounts/1
  # ENABLE /accounts/1.json
  def enable
    @bill.update_attribute :is_recurring, true
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to account_path(@bill.account_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:user_id, :amount_string, :account_id, :is_recurring, :payee_name, :payee_street, :payee_city, :payee_state, :payee_zip, :payee_account_id, :pay_date)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bills.html.erb
<h2>Bills</h2>

<% @bills.each do |bill| %>
    <%= link_to "Bill to #{bill.payee_name} : Amount #{number_to_currency(bill.amount)} : From #{Account.find(bill.account_id).display_account_id}", bill%>
<% end %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3><%= @user.display_account_id %></h3>
  
  <div class="field">
    <%= f.label :account_id, "From Account" %><br/>
    <%= f.select( :account_id, @accounts.all.collect { |i| ["#{i.id} : #{number_to_currency(i.current_balance)}", i.id]} ) %>
  </div>

  <div class="field">
    <%= f.label :payee_name %><br>
    <%= f.text_field :payee_name %>
  </div>
  <div class="field">
    <%= f.label :payee_street %><br>
    <%= f.text_field :payee_street %>
  </div>
  <div class="field">
    <%= f.label :payee_city %><br>
    <%= f.text_field :payee_city %>
  </div>
  <div class="field">
    <%= f.label :payee_state %><br>
    <%= f.text_field :payee_state %>
  </div>
  <div class="field">
    <%= f.label :payee_zip %><br>
    <%= f.text_field :payee_zip %>
  </div>
  <div class="field">
    <%= f.label :payee_account_id %><br>
    <%= f.number_field :payee_account_id %>
  </div>
  <div class="field">
    <%= f.label :amount_string %><br>
    <%= f.text_field :amount_string %>
  </div>
  <div class="field">
    <%= f.label :pay_date %><br>
    <%= f.date_select :pay_date %>
  </div>

  <div class="field">
    <%= f.label :is_recurring %><br>
    <%= f.check_box :is_recurring %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<div class="main control-panel">
    <h1>Editing bill</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Show', @bill %>
</div>

app/views/bills/index.html.erb
<div class="main control-panel">
    <%= render :partial => "bills" %>
</div>

app/views/bills/new.html.erb
<div class="main control-panel">
    <h2>New Bill</h2>

<%= render 'form' %>

app/views/bills/show.html.erb
<div class="main control-panel">
  <p id="notice"><%= notice %></p>
  <h2>Bill Information</h2>
  <p>
    <strong>User:</strong>
    <%= User.find(@bill.user_id).username %><br/>
    <strong>Account:</strong>
    <%= Account.find(@bill.account_id).display_account_id %><br/>
    <strong>Payee name:</strong>
    <%= @bill.payee_name %><br/>
    <strong>Payee street:</strong>
    <%= @bill.payee_street %><br/>
    <strong>Payee city:</strong>
    <%= @bill.payee_city %><br/>
    <strong>Payee state:</strong>
    <%= @bill.payee_state %><br/>
    <strong>Payee zip:</strong>
    <%= @bill.payee_zip %><br/>
    <strong>Payee account:</strong>
    <%= @bill.payee_account_id %><br/>
    <strong>Amount:</strong>
    <%= @bill.amount %><br/>
    <strong>Pay date:</strong>
    <%= @bill.pay_date %><br/>
    <strong>Is recurring:</strong>
    <%= @bill.is_recurring %><br/>
  </p>
  <%= link_to 'Edit', edit_bill_path(@bill) %>
  <% if @bill.is_recurring == true %>
      <%= link_to 'Stop Recurrence', stop_recurrence_path(@bill) %>
  <% else -%>
      <%= link_to 'Start Recurrence', start_recurrence_path(@bill) %>
  <% end %>
  <%= link_to 'Delete', @bill, :confirm => 'Are you sure?', :method => :delete %>
  <%= link_to 'Back', account_path(@bill.account_id) %>
</div>